import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import "@radix-ui/themes/styles.css";
import { Theme } from "@radix-ui/themes";
import Link from "next/link";
import { Button } from "@/components/ui/button";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <Theme appearance="light" accentColor="indigo" radius="large">
          <header className="border-b">
            <div className="mx-auto max-w-6xl px-4 py-3 flex items-center justify-between">
              <Link href="/" className="font-semibold">Dashboard</Link>
              <nav className="flex items-center gap-2">
                <Button variant="ghost" asChild>
                  <Link href="/authors">Autores</Link>
                </Button>
                <Button variant="ghost" asChild>
                  <Link href="/books">Libros</Link>
                </Button>
              </nav>
            </div>
          </header>
          <main>
            {children}
          </main>
        </Theme>
      </body>
    </html>
  );
}
